# MSM_ch - Configuration
  # Log level - specifies what will be output to the console.
  # Errors will always be logged to file regardless, except at loglevel 0.
  # 3 - Log debug messages.
  # 2 - Log errors to console.
  # 1 - Log only warnings and informational messages. Errors logged to file.
  # 0 - Log only informational messages. Errors are not logged at all.
  loglevel: 2

  # Usernames which should be marked as bots. Should begin with a '~'.
  bots:
    - ~console

  # Developer IPs. IPs in this list will be able to use developer tools.
  devips:
    - 127.0.0.1
  # Enabled mechanics
  explosives: false
  fire: true
  firespread: false
  fluidspread: false
  water: true
  lava: true
  plants: true

